apiVersion: 1

datasources:
  - name: PostgreSQL
    type: PostgreSQL
    access: proxy
    url: db.:5432
    database: test
    user: postgres
    secureJsonData:
      password: 'example'
    jsonData:
      sslmode: 'disable'